[firestore]
ibes_actpsum = "https://firebasestorage.googleapis.com/v0/b/website-ffbc5.appspot.com/o/ibes_actpsum_USD.pkl.gz?alt=media&token=8c97ee6f-20db-489d-b0ba-3a080dd3d7ad"
ibse_statsum = "https://firebasestorage.googleapis.com/v0/b/website-ffbc5.appspot.com/o/ibes_statsum_USD.pkl.gz?alt=media&token=73db9cea-80df-48e0-981f-a327b3750c84"
